micronaut:
  application:
    name: bugDemo

datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "demo"
    password: "demo123"
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

logger:
  levels:
    io.micronaut.data: TRACE